# PDF Documentation Generation Configuration
# Defines profiles for generating PDF documentation packages

profiles:
  # Offline Installation Profile
  # For customers doing air-gapped/offline installations
  offline-install:
    name: "Kamiwaza Offline Installation Guide"
    description: "Essential documentation for offline installations"
    filename: "kamiwaza-offline-install"
    cover:
      title: "Kamiwaza AI Platform"
      subtitle: "Offline Installation Guide"
      includeVersion: true
      includeLogo: true
    documents:
      - id: "admin-guide"
        title: "Administrator Guide"
      - id: "installation/system_requirements"
        title: "System Requirements"
      - id: "installation/installation_process"
        title: "Installation Process"
      - id: "installation/gpu_setup_guide"
        title: "GPU Setup Guide"
      - id: "quickstart"
        title: "Quickstart Guide"
      - id: "release-notes"
        title: "Release Notes"
    options:
      includeTOC: true
      includePageNumbers: true
      includeHeaders: true
      includeFooters: true
      pageNumberStart: 1

  # Full Documentation Profile
  # Complete platform documentation
  full-docs:
    name: "Kamiwaza AI Platform Documentation"
    description: "Complete platform documentation"
    filename: "kamiwaza-docs-complete"
    cover:
      title: "Kamiwaza AI Platform"
      subtitle: "Complete Documentation"
      includeVersion: true
      includeLogo: true
    documents:
      - id: ""
        title: "Introduction"
      - id: "installation/system_requirements"
        title: "System Requirements"
      - id: "installation/installation_process"
        title: "Installation Process"
      - id: "installation/linux_macos_tarball"
        title: "Linux/macOS Installation"
      - id: "installation/windows_installation_guide"
        title: "Windows Installation"
      - id: "installation/gpu_setup_guide"
        title: "GPU Setup Guide"
      - id: "quickstart"
        title: "Quickstart Guide"
      - id: "models/overview"
        title: "Models Overview"
      - id: "models/novice-mode"
        title: "Novice Mode"
      - id: "models/gui-walkthrough"
        title: "GUI Walkthrough"
      - id: "models/downloading-models"
        title: "Downloading Models"
      - id: "models/deployment"
        title: "Model Deployment"
      - id: "models/troubleshooting"
        title: "Model Troubleshooting"
      - id: "app-garden"
        title: "App Garden"
      - id: "data-engine"
        title: "Distributed Data Engine"
      - id: "use-cases/index"
        title: "Use Cases"
      - id: "use-cases/building-a-rag-pipeline"
        title: "Building a RAG Pipeline"
      - id: "architecture/overview"
        title: "Architecture Overview"
      - id: "architecture/components"
        title: "Platform Components"
      - id: "architecture/core-services"
        title: "Core Services"
      - id: "admin-guide"
        title: "Administrator Guide"
      - id: "other-topics"
        title: "Other Topics"
      - id: "help-and-fixes"
        title: "Help & Fixes"
      - id: "release-notes"
        title: "Release Notes"
    options:
      includeTOC: true
      includePageNumbers: true
      includeHeaders: true
      includeFooters: true
      pageNumberStart: 1

# Global PDF Settings
settings:
  # Default version (can be overridden via CLI)
  defaultVersion: "current"

  # Output directory (relative to project root)
  outputDir: "dist/pdf"

  # PDF generation options
  pdf:
    format: "A4"
    margin:
      top: "20mm"
      right: "15mm"
      bottom: "20mm"
      left: "15mm"
    printBackground: true
    preferCSSPageSize: false

  # Server settings for local build
  server:
    port: 9003
    baseUrl: "http://localhost:9003"

  # Styling
  css:
    customStylesheet: "docs/src/css/pdf.css"
