#!/usr/bin/env npx ts-node

/**
 * Sync OpenAPI spec from kamiwaza repo for API documentation generation.
 *
 * The OpenAPI spec is generated dynamically by the Kamiwaza platform (FastAPI),
 * so we sync from the local working directory. To sync from a specific branch:
 * 1. Checkout the desired branch in the kamiwaza repo
 * 2. Run the platform to generate openapi.json (or use existing generated file)
 * 3. Run this script without arguments
 *
 * Usage:
 *   npx ts-node scripts/sync-openapi.ts [--generate]
 *
 * Options:
 *   --generate    Generate fresh openapi.json by starting the platform (requires running services)
 *
 * Examples:
 *   npx ts-node scripts/sync-openapi.ts                    # Uses existing openapi.json from local repo
 *   npx ts-node scripts/sync-openapi.ts --generate         # Generates fresh spec from running platform
 *
 * To sync from a specific release:
 *   cd ../platform/kamiwaza && git checkout release/0.9.3
 *   # Ensure openapi.json is generated (run platform or use existing)
 *   cd ../docs/kamiwaza-docs && npm run sync-openapi
 *
 * Environment variables:
 *   KAMIWAZA_REPO_PATH - Path to local kamiwaza repo (default: ../platform/kamiwaza)
 *   KAMIWAZA_API_URL   - URL to fetch OpenAPI spec from (default: http://localhost:7777/openapi.json)
 */

import { execFileSync } from "child_process";
import fs from "fs-extra";
import path from "path";

const OPENAPI_FILENAME = "openapi.json";
const TARGET_DIR = path.resolve(__dirname, "../docs/api");
const TARGET_FILE = path.join(TARGET_DIR, OPENAPI_FILENAME);

function resolveKamiwazaRepoPath(): string {
	const override = process.env.KAMIWAZA_REPO_PATH;
	const candidates = [
		override,
		path.resolve(__dirname, "../../platform/kamiwaza"),
		path.resolve(__dirname, "../../../platform/kamiwaza"),
		path.resolve(__dirname, "../../kamiwaza"),
	].filter(Boolean) as string[];

	for (const candidate of candidates) {
		if (fs.existsSync(path.join(candidate, ".git"))) {
			return candidate;
		}
	}

	const tried = candidates.map((c) => `  - ${c}`).join("\n");
	throw new Error(
		`Unable to locate kamiwaza repo. Set KAMIWAZA_REPO_PATH or place the repo in one of the expected locations:\n${tried}`,
	);
}

function getCurrentBranch(repoPath: string): string {
	try {
		const result = execFileSync("git", ["rev-parse", "--abbrev-ref", "HEAD"], {
			cwd: repoPath,
			encoding: "utf-8",
			stdio: ["pipe", "pipe", "pipe"],
		});
		return result.trim();
	} catch {
		return "unknown";
	}
}

async function fetchFromRunningPlatform(): Promise<string> {
	const apiUrl =
		process.env.KAMIWAZA_API_URL || "http://localhost:7777/openapi.json";
	console.log(`Fetching OpenAPI spec from running platform: ${apiUrl}`);

	const response = await fetch(apiUrl);
	if (!response.ok) {
		throw new Error(
			`Failed to fetch from ${apiUrl}: ${response.status} ${response.statusText}`,
		);
	}
	return response.text();
}

function getOpenAPIFromLocalRepo(repoPath: string): string {
	const openapiPath = path.join(repoPath, OPENAPI_FILENAME);
	const branch = getCurrentBranch(repoPath);

	console.log(`Using OpenAPI spec from local repo: ${repoPath}`);
	console.log(`  Current branch: ${branch}`);

	if (!fs.existsSync(openapiPath)) {
		throw new Error(
			`OpenAPI spec not found at: ${openapiPath}\n\n` +
				`The openapi.json file is generated by the Kamiwaza platform.\n` +
				`To generate it:\n` +
				`  1. Start the platform: cd ${repoPath} && make start-core\n` +
				`  2. Run this script with --generate flag\n` +
				`Or copy an existing openapi.json to the repo root.`,
		);
	}
	return fs.readFileSync(openapiPath, "utf-8");
}

function getDocsVersion(): string {
	// Read version from package.json
	const packageJsonPath = path.resolve(__dirname, "../package.json");
	try {
		const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, "utf-8"));
		return packageJson.version || "0.9.3";
	} catch {
		return "0.9.2";
	}
}

async function main() {
	const args = process.argv.slice(2);
	const generateFromPlatform = args.includes("--generate");

	console.log("=== Kamiwaza OpenAPI Sync ===\n");

	// Find kamiwaza repo
	const repoPath = resolveKamiwazaRepoPath();
	console.log(`Kamiwaza repo: ${repoPath}`);

	// Get OpenAPI spec
	let content: string;
	if (generateFromPlatform) {
		content = await fetchFromRunningPlatform();
	} else {
		content = getOpenAPIFromLocalRepo(repoPath);
	}

	// Parse and validate
	let spec: any;
	try {
		spec = JSON.parse(content);
	} catch (e) {
		throw new Error(`Invalid JSON in OpenAPI spec: ${e}`);
	}

	if (!spec.openapi || !spec.paths) {
		throw new Error("Invalid OpenAPI spec: missing required fields");
	}

	// Patch the API version to match docs version
	const docsVersion = getDocsVersion();
	const originalVersion = spec?.info?.version || "unknown";
	if (spec.info) {
		spec.info.version = docsVersion;
	}

	const pathCount = Object.keys(spec.paths).length;
	const schemaCount = Object.keys(spec.components?.schemas || {}).length;

	console.log(`\nOpenAPI spec info:`);
	console.log(`  - OpenAPI version: ${spec.openapi}`);
	console.log(`  - Original API version: ${originalVersion}`);
	console.log(`  - Patched API version: ${docsVersion}`);
	console.log(`  - Endpoints: ${pathCount}`);
	console.log(`  - Schemas: ${schemaCount}`);

	// Ensure target directory exists
	await fs.ensureDir(TARGET_DIR);

	// Write the spec
	await fs.writeFile(TARGET_FILE, JSON.stringify(spec, null, 2));
	console.log(`\nWritten to: ${TARGET_FILE}`);

	// Get source branch for metadata
	const sourceBranch = getCurrentBranch(repoPath);

	// Create a metadata file for tracking
	const metadata = {
		syncedAt: new Date().toISOString(),
		sourceRepo: repoPath,
		sourceBranch: generateFromPlatform ? "running-platform" : sourceBranch,
		originalApiVersion: originalVersion,
		patchedApiVersion: docsVersion,
		endpoints: pathCount,
		schemas: schemaCount,
	};
	await fs.writeFile(
		path.join(TARGET_DIR, "openapi-metadata.json"),
		JSON.stringify(metadata, null, 2),
	);

	console.log("\nSync complete!");
	console.log("\nNext steps:");
	console.log("  1. Run `npm run build` to regenerate API docs");
	console.log("  2. Review changes at /sdk/api-reference");
}

main().catch((err) => {
	console.error("\nError:", err.message);
	process.exit(1);
});
